server:
  port: 8081

spring:
  application:
    name: category-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cms_db;encrypt=true;trustServerCertificate=true
    username: cms
    password: Welcome@2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none  # ✅ Use 'none' since schema is already created
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
